### ISSUE TITLE
showing error on server

### ISSUE THREAD

**Issue by soubhagyabarik** [braintreedev/sample-12-paypal-adaptive-payments-chained-parallel-php#1]
cURL error (35): SSL connect error

i have tried this and it's working fine in local system but on server it's shwing error 
> cURL error (35): SSL connect error
really need help

**Comment by developersteve** [comment]
@soubhagyabarik probably need to check with @braintree on this as Braintreedev was shut down by them a year and half ago

**Comment by soubhagyabarik** [comment]
@developersteve can you please give me the particular link

**Comment by developersteve** [comment]
@soubhagyabarik lol click braintree in my response

**Comment by soubhagyabarik** [comment]
@developersteve i am talking about the particular link where i can find answer regarding my issue

**Comment by developersteve** [comment]
See https://github.com/braintreedev/sample-12-paypal-adaptive-payments-chained-parallel-php/issues/1#issuecomment-319924118

**Comment by rakeshkumar125** [comment]
It's not working. I gives error after payment return below url

cmd=_flow&SESSION=qxzelc9b8QYb7QrT412jGSgPnPzmO_kZWXNje-yttiGRSCqJLYujNlDa5fS&dispatch=5885d80a13c0db1f8e263663d3faee8db8175432b4df92754f4b4adb5a123d61&rapidsState=AdaptivePayment__NewUI__ApprovePayRequestFlow___StateMakePayment&rapidsStateSignature=(null)

**Comment by devchristina** [comment]
Closing this issue, this repo is on a path to being archived.
